<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>log</string>
		<string>txt</string>
	</array>
	<key>name</key>
	<string>Huawei Session</string>
	<key>patterns</key>
	<array>

		<dict>
			<key>match</key>
			<string>device transceiver .*</string>
			<key>name</key>
			<string>variable.huawei</string>
		</dict>
		<dict>
			<key>match</key>
			<string>interface is [Up|Down].</string>
			<key>name</key>
			<string>invalid.deprecated.huawei</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(ip vpn-instance \S+)|(vpn-instance \S+)</string>
			<key>name</key>
			<string>variable.parameter.huawei</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\d+\.\d+\.\d+\.\d+</string>
			<key>name</key>
			<string>constant.character.escape.huawei</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\S+\></string>
			<key>name</key>
			<string>string.huawei</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s+[Uu][Pp]\s+)|(\s+Established\s+)|(\s+forwarding\s+)|(\s+enable\s+)</string>
			<key>name</key>
			<string>entity.other.attribute-name.huawei</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s+[Dd]own\s+)|(\s+DOWN\s+)|(\s+clock status: unsynchronized\s+)|(\s+disable\s+)|(unsynchronized)|(shutdown)|(undo enable)</string>
			<key>name</key>
			<string>keyword.huawei</string>
		</dict>

		<dict>
			<key>match</key>
			<string>(interface \S+)|(^bridge-domain \d+)|(^dfs-group \S+)</string>
			<key>name</key>
			<string>support.function.huawei</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s+[Uu][Pp]\s+)|(\s+Established\s+)|(\s+forwarding\s+)|(PEER_ESTABLISHED_NOTIFICATION.*)</string>
			<key>name</key>
			<string>entity.name.function.huawei</string>
		</dict>

		
		<!-- STP -->
		<dict>
			<key>match</key>
			<string>This bridge is the root</string>
			<key>name</key>
			<string>entity.name.class.huawei</string>
		</dict>
		<dict>
			<key>match</key>
			<string>Port.*FORWARDING</string>
			<key>name</key>
			<string>entity.name.function.huawei</string>
		</dict>
		<dict>
			<key>match</key>
			<string>Port.*LEARNING</string>
			<key>name</key>
			<string>invalid.function.huawei</string>
		</dict>
		<dict>
			<key>match</key>
			<string>Port.*DISCARDING</string>
			<key>name</key>
			<string>invalid.huawei</string>
		</dict>
		<dict>
			<key>match</key>
			<string>Port\S+DOWN</string>
			<key>name</key>
			<string>string.huawei</string>
		</dict>

		<!-- CHECK 
		<dict>
			<key>match</key>
			<string>\[.*\]</string>
			<key>name</key>
			<string>string.huawei</string>
		</dict>
		-->
		<dict>
			<key>match</key>
			<string></string>
			<key>name</key>
			<string>string.unquoted.huawei</string>
		</dict>
		<dict>
			<key>match</key>
			<string></string>
			<key>name</key>
			<string>string.unquoted.huawei</string>
		</dict>
		<dict>
			<key>match</key>
			<string>Command=".*"</string>
			<key>name</key>
			<string>string.unquoted.huawei</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(display .*)|(dis .*)</string>
			<key>name</key>
			<string>variable.parameter.huawei</string>
		</dict>
		<dict>
			<key>match</key>
			<string>Eth-Trunk\S+</string>
			<key>name</key>
			<string>string.unquoted.huawei</string>
		</dict>
		<dict>
			<key>match</key>
			<string></string>
			<key>name</key>
			<string>support.function.huawei</string>
		</dict>
		<dict>
			<key>match</key>
			<string>access-list</string>
			<key>name</key>
			<string>support.function.huawei</string>
		</dict>
		<dict>
			<key>match</key>
			<string></string>
			<key>name</key>
			<string>support.constant.huawei</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\S\S\S\s+\d+\s+\d+ \d\d:\d\d:\d\d</string>
			<key>name</key>
			<string>constant.character.escape.huawei</string>
		</dict>

		<dict>
			<key>match</key>
			<string>(\S+ V\S+R\S+)|(HUAWEI \S+)|</string>
			<key>name</key>
			<string>entity.name.function.huawei</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[#!](.*)</string>
			<key>name</key>
			<string>comment.line.huawei</string>
		</dict>
		<dict>
			<key>match</key>
			<string>cipher (\S)*</string>
			<key>name</key>
			<string>comment.line.huawei</string>
		</dict>




		<dict>
			<key>match</key>
			<string>\s+[A-Z\-_0-9/]+[A-Z\-_]+[A-Z\-_0-9]+\s+</string>
			<key>name</key>
			<string>string.huawei</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.huawei</string>
	<key>uuid</key>
	<string>f3ba50f0-2bad-48b7-9509-f6d72e353ddb</string>
</dict>
</plist>
