<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>log</string>
		<string>txt</string>
	</array>
	<key>name</key>
	<string>Huawei dot1x</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\s+[A-Z\-_0-9/]+[A-Z\-_]+[A-Z\-_0-9]+\s+</string>
			<key>name</key>
			<string>storage.type.huawei</string>

	</array>
	<key>scopeName</key>
	<string>text.huawei</string>
	<key>uuid</key>
	<string>f3ba50f0-2bad-48b7-9509-f6d72e353ddb</string>
</dict>
</plist>
